#!/usr/bin/env python3

import pyperclip, getpass, webbrowser

def Password():
	p = getpass.getpass(prompt='Password: ')
	if p == '1234':
		PrintingandSorting()
	else:
		Ending()

def Ending():
	print('Goodbye!!!')
	return 0

def Define(List):
	for item in List:
		Address = item
		webbrowser.get('firefox').open_new_tab('https://www.merriam-webster.com/dictionary/' + Address)
	Ending()

def PrintingandSorting():
	List = []
	check = ''
	recheck = ''
	Amount = int(input('How many words do you want to define? Enter number: '))
	while True:
		check = pyperclip.paste()
		if check != recheck:
			List.append(check)
		else:
			continue
		recheck = check
		Occurances = List.count(check)
		if Occurances >= 2:
			foo = input('The word: ' + check + ' already exists. Do you wish to add more words? Y/N: ')
			if foo == 'Y' or foo == 'y':
				continue
			else:
				break
		print(check)
		if len(List) >= Amount:
			Ask = input('Do you wish to add more? Y/N: ')
			if Ask == 'Y' or Ask == 'y':
				Amount = Amount + 5
				continue
			else:
				break
	
	List.pop()
	print(List)
	Clearence = input('Are these the words you want to define? Y/N: ')
	if Clearence == 'Y' or Clearence == 'y':
		Define(List)
	else:
		PrintingandSorting()

Password()
